drivers: power-udi_v2: mtk_udi: Prevent sscanf overflow
../../../../../../kernel/xiaomi/mt6785/drivers/misc/mediatek/base/power/udi_v2/mtk_udi.c:481:18: error: 'sscanf' may overflow; destination buffer in argument 9 has size
 512, but the corresponding specifier may require size 513 [-Werror,-Wfortify-source]
                        &recv_buf[2], recv_char[1], &recv_buf[4]) == 8) {
                                      ^
../../../../../../kernel/xiaomi/mt6785/drivers/misc/mediatek/base/power/udi_v2/mtk_udi.c:488:18: error: 'sscanf' may overflow; destination buffer in argument 8 has size
 512, but the corresponding specifier may require size 513 [-Werror,-Wfortify-source]
                        &recv_buf[2], recv_char[1]) == 6) {
                                      ^

Signed-off-by: DarkJoker360 <simoespo159@gmail.com>